{{- if ne .Values.global.registry_location "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    heritage: deis
  annotations:
    deis.io/registry-location: "{{ .Values.global.registry_location }}"
type: Opaque
data: {{ if eq .Values.global.registry_location "gcr" }}
  key.json: {{ .Values.gcr.key_json }}
  hostname: {{ .Values.gcr.hostname | b64enc }}{{ else if eq .Values.global.registry_location "ecr" }}
  accesskey: {{ .Values.ecr.accesskey | b64enc }}
  secretkey: {{ .Values.ecr.secretkey | b64enc }}
  region: {{ .Values.ecr.region | b64enc }}
  registryid: {{ .Values.ecr.registryid | b64enc }}
  hostname: {{ .Values.ecr.hostname | b64enc }}{{else if eq .Values.global.registry_location "off-cluster" }}
  hostname: {{ .Values.off_cluster_registry.hostname | b64enc }}
  organization: {{ .Values.off_cluster_registry.organization | b64enc }}
  username: {{ .Values.off_cluster_registry.username | b64enc }}
  password: {{ .Values.off_cluster_registry.password | b64enc }}{{ end }}
{{- end }}
