apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerbuilder-config
  labels:
    heritage: deis
data:
  image: "quay.io/{{.Values.org}}/dockerbuilder:{{.Values.docker_tag}}"
  pullpolicy: {{ .Values.pull_policy }}
