apiVersion: v1
kind: Service
metadata:
  name: deis-builder
  labels:
    heritage: deis
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2223
  selector:
    app: deis-builder
{{ if .Values.global.experimental_native_ingress }}
  type: "LoadBalancer"
{{ end }}
