apiVersion: v1
kind: Secret
metadata:
  name: builder-key-auth
  labels:
    heritage: deis
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  builder-key: {{ randAlphaNum 64 | b64enc }}
