{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: Role
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: deis-monitor-telegraf
  labels:
    app: deis-monitor-telegraf
    heritage: deis
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
{{- end -}}
{{- end -}}
{{- if (.Values.global.use_openshift_rbac) -}}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app: deis-monitor-telegraf
    heritage: deis
  name: deis-monitor-telegraf
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - get
{{- end -}}
