{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: RoleBinding
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: deis-monitor-telegraf
  labels:
    app: deis-monitor-telegraf
    heritage: deis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deis-monitor-telegraf
subjects:
- kind: ServiceAccount
  name: deis-monitor-telegraf
{{- end -}}
{{- end -}}
{{- if (.Values.global.use_openshift_rbac) -}}
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: deis-monitor-telegraf
    heritage: deis
  name: deis-monitor-telegraf
roleRef:
  name: deis-monitor-telegraf
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: deis-monitor-telegraf
  namespace: {{ .Release.Namespace }}
{{- end -}}
