{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
apiVersion: {{ template "rbacAPIVersion" . }}
kind: Role
metadata:
  labels:
    app: deis-router
    heritage: deis
  name: deis-router
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get"]
{{- end -}}
{{- end -}}
{{- if (.Values.global.use_openshift_rbac) -}}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app: deis-router
    heritage: deis
  name: deis-router
rules:
- apiGroups:
  - extensions
  - apps
  attributeRestrictions: null
  resources:
  - deployments
  verbs:
  - get
{{- end -}}
