{{- if eq .Values.global.grafana_location "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-grafana
  labels:
    heritage: deis
    app: deis-monitor-grafana
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: grafana
    router.deis.io/connectTimeout: "10"
    router.deis.io/tcpTimeout: "1200"
spec:
  ports:
  - port: 80
    name: ui
    targetPort: ui
  selector:
    app: deis-monitor-grafana
{{- end }}
