apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  labels:
    heritage: deis
type: Opaque
data:
  accesskey: OFRaUlkySlJXTVBUNlVNWFI2STU=
  secretkey: Z2JzdHJPdm90TU1jZzJzTWZHVWhBNWE2RXQvRUk1QUx0SUhzb2JZaw==
