apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-nsqd
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-nsqd
  template:
    metadata:
      labels:
        app: deis-nsqd
    spec:
      serviceAccount: deis-nsqd
      containers:
        - name: deis-nsqd
          image: quay.io/{{.Values.org}}/nsq:{{.Values.docker_tag}}
          imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          command:
          - /opt/nsq/bin/start-nsqd
          ports:
          - containerPort: 4151
            name: http
            protocol: TCP
          - containerPort: 4150
            name: transport
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 4151
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 4151
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
