{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: ClusterRole
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: deis:deis-controller
  labels:
    app: deis-controller
    heritage: deis
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["replicationcontrollers"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["replicationcontrollers/scale"]
  verbs: ["get", "update"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "create"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "delete", "update"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments/scale", "replicasets/scale"]
  verbs: ["get", "update"]
- apiGroups: ["extensions", "autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "create", "update", "delete"]
{{ if .Values.global.experimental_native_ingress }}
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
{{- end -}}
{{- end -}}
{{- end -}}
{{- if (.Values.global.use_openshift_rbac) -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: deis-controller
    heritage: deis
  name: deis:deis-controller
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - replicationcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - replicationcontrollers/scale
  verbs:
  - get
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - resourcequotas
  verbs:
  - create
  - get
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - replicasets
  verbs:
  - delete
  - get
  - list
  - update
- apiGroups:
  - extensions
  - apps
  attributeRestrictions: null
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - deployments/scale
  - replicasets/scale
  verbs:
  - get
  - update
- apiGroups:
  - extensions
  - autoscaling
  attributeRestrictions: null
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - update
{{- end -}}
