{{- if eq .Values.global.influxdb_location "on-cluster" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-monitor-influxdb
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-monitor-influxdb
  template:
    metadata:
      labels:
        app: deis-monitor-influxdb
    spec:
      containers:
      - name: deis-monitor-influxdb
        image: quay.io/{{.Values.org}}/influxdb:{{.Values.docker_tag}}
        imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        ports:
        - containerPort: 8083
          name: admin
        - containerPort: 8086
          name: transport
          protocol: TCP
        - containerPort: 8084
          name: ssltransport
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 1
          timeoutSeconds: 1
{{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: influxdb-data
          mountPath: /data
      # Allow user influxdb to write to /data
      securityContext:
        fsGroup: 1001
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: deis-monitor-influxdb
{{- end }}
{{- end }}
